---

########################################################
# Helper variables
private_ip: '{{ ansible_default_ipv4.address }}'

managers_hostvars: "{{ groups['managers'] | map('extract', hostvars)  | list }}"
elastic_hostvars: "{{ groups['elastic'] | map('extract', hostvars)  | list }}"
kibana_hostvars: "{{ groups['kibana'] | map('extract', hostvars)  | list }}"

manager_addresses: "{{ managers_hostvars | map(attribute='private_ip') | list }}"
elastic_addresses: "{{ elastic_hostvars | map(attribute='private_ip') | list }}"
kibana_addresses: "{{ kibana_hostvars | map(attribute='private_ip') | list }}"

########################################################
# General ELK stack variables

# Cluster Settings
#es_version: "7.9.1"
#es_major_version: "7.x"
#opendistro_version: 1.10.1
filebeat_version: 7.9.1

# OpenDistro
kibana_opendistro_security: true

opendistro_kibana_user: kibanaserver
opendistro_security_user: elastic

opendistro_kibana_password: changeme
opendistro_security_password: admin
opendistro_admin_password: changeme

# All nodes are called by IP name
elasticsearch_node_name: '{{ ansible_hostname }}'
kibana_node_name: '{{ ansible_hostname }}'
filebeat_node_name: '{{ ansible_hostname }}'